[mapper_lad_code]
old_name = "LAD25CD"
Deduced_Data_Type = "str"

[mapper_lad_name]
old_name = "LAD25NM"
Deduced_Data_Type = "str"

[mapper_lau_code]
old_name = "LAU125CD"
Deduced_Data_Type = "str"

[mapper_lau_name]
old_name = "LAU125NM"
Deduced_Data_Type = "str"
