[mapper_lad_code]
old_name = "LAD20CD"
Deduced_Data_Type = "str"

[mapper_lad_name]
old_name = "LAD20NM"
Deduced_Data_Type = "str"

[mapper_lau_code]
old_name = "LAU121CD"
Deduced_Data_Type = "str"

[mapper_lau_name]
old_name = "LAU121NM"
Deduced_Data_Type = "str"
