title = "Developer configuration file"
description = "Configuration file with options the user is not expected to change, intended for developers."

[database]
database_name = "projectdatabase"
input_table = "input_table_name"
output_table = "output_table_name"

[filepaths]
output_directory = "/dap/workspace_zone/project/outputs"
logfile_directory = "/dap/workspace_zone/project/runlogs"
