[lsoa21]
old_name = "lsoa21"
Deduced_Data_Type = "str"

[year]
old_name = "Year"
Deduced_Data_Type = "str"

[component]
old_name = "Component"
Deduced_Data_Type = "str"

[value]
old_name = "Value"
Deduced_Data_Type = "int"

[lAD_total]
old_name = "LAD_total"
Deduced_Data_Type = "int"